import type { SceneObject, Template, SceneLight } from "./editor-store";

const baseObj = {
  emissive: "#000000",
  emissiveIntensity: 0,
  clearcoat: 0,
  clearcoatRoughness: 0.1,
  transmission: 0,
  ior: 1.5,
  thickness: 0.5,
  envMapIntensity: 1,
  texture: "none" as const,
  textureRepeat: 1,
  bob: 0,
  castShadow: true,
  receiveShadow: true,
};

type O = Omit<SceneObject, "id">;
type L = Omit<SceneLight, "id">;

const o = (p: Partial<O> & Pick<O, "name" | "type">): O => ({
  position: [0, 0.5, 0],
  rotation: [0, 0, 0],
  scale: [1, 1, 1],
  color: "#e5e5e5",
  metalness: 0.4,
  roughness: 0.35,
  spin: [0, 0, 0],
  ...baseObj,
  ...p,
});

const ground = (color: string, extras: Partial<O> = {}): O =>
  o({
    name: "ground", type: "plane",
    position: [0, 0, 0], rotation: [-Math.PI / 2, 0, 0], scale: [40, 40, 1],
    color, metalness: 0.1, roughness: 0.85, castShadow: false,
    ...extras,
  });

// Light rigs ------------------------------------------------------
const rigs = {
  studio: (): L[] => [
    { name: "ambient", type: "ambient", position: [0, 0, 0], color: "#ffffff", intensity: 0.3, castShadow: false },
    { name: "key", type: "directional", position: [6, 8, 5], color: "#ffffff", intensity: 1.6, castShadow: true },
    { name: "fill", type: "directional", position: [-6, 4, 3], color: "#ffeacc", intensity: 0.5, castShadow: false },
    { name: "rim", type: "directional", position: [0, 5, -7], color: "#88aaff", intensity: 0.8, castShadow: false },
  ],
  noir: (): L[] => [
    { name: "ambient", type: "ambient", position: [0, 0, 0], color: "#0a0a18", intensity: 0.15, castShadow: false },
    { name: "key", type: "spot", position: [4, 9, 3], color: "#ffffff", intensity: 8, castShadow: true, angle: 0.6, penumbra: 0.4, distance: 30, decay: 1.2 },
    { name: "rim", type: "directional", position: [-4, 2, -5], color: "#ff3a8a", intensity: 0.6, castShadow: false },
  ],
  neon: (): L[] => [
    { name: "ambient", type: "ambient", position: [0, 0, 0], color: "#1a0033", intensity: 0.4, castShadow: false },
    { name: "magenta", type: "point", position: [4, 3, 2], color: "#ff00aa", intensity: 8, castShadow: false, distance: 15, decay: 1.5 },
    { name: "cyan", type: "point", position: [-4, 3, 2], color: "#00ffff", intensity: 8, castShadow: false, distance: 15, decay: 1.5 },
    { name: "key", type: "directional", position: [0, 6, 4], color: "#ffffff", intensity: 0.4, castShadow: true },
  ],
  golden: (): L[] => [
    { name: "ambient", type: "ambient", position: [0, 0, 0], color: "#ffeacc", intensity: 0.4, castShadow: false },
    { name: "sun", type: "directional", position: [-5, 6, 4], color: "#ffb060", intensity: 2.2, castShadow: true },
    { name: "fill", type: "directional", position: [5, 3, 2], color: "#5070ff", intensity: 0.4, castShadow: false },
  ],
  arctic: (): L[] => [
    { name: "ambient", type: "ambient", position: [0, 0, 0], color: "#cce4ff", intensity: 0.5, castShadow: false },
    { name: "sky", type: "directional", position: [4, 9, 4], color: "#ffffff", intensity: 1.4, castShadow: true },
    { name: "bounce", type: "directional", position: [-4, 0, -3], color: "#88c0ff", intensity: 0.4, castShadow: false },
  ],
};

export const TEMPLATES: Template[] = [
  {
    id: "obsidian-monolith",
    name: "Obsidian Monolith",
    tags: ["dark", "cinematic", "hero"],
    background: "#030305", environment: "night", exposure: 1.1,
    fx: { bloom: true, bloomIntensity: 0.8, vignette: true, chromatic: true, chromaticOffset: 0.0015 },
    lights: rigs.noir(),
    objects: [
      ground("#050505", { metalness: 0.3, roughness: 0.4 }),
      o({ name: "monolith", type: "box", position: [0, 1.6, 0], scale: [1, 3.2, 0.4],
          color: "#0a0a0a", metalness: 0.95, roughness: 0.06, clearcoat: 1, envMapIntensity: 1.4 }),
      o({ name: "halo", type: "torus", position: [0, 1.6, 0], rotation: [Math.PI / 2, 0, 0],
          scale: [2.4, 2.4, 2.4], color: "#ffffff", emissive: "#ffffff", emissiveIntensity: 0.8,
          metalness: 0, roughness: 1, spin: [0, 0.2, 0] }),
    ],
  },
  {
    id: "liquid-chrome",
    name: "Liquid Chrome",
    tags: ["chrome", "studio", "abstract"],
    background: "#101015", environment: "warehouse", exposure: 1,
    fx: { bloom: true, bloomIntensity: 1.1, vignette: true },
    lights: rigs.studio(),
    objects: [
      ground("#101015", { metalness: 0.6, roughness: 0.2 }),
      o({ name: "blob", type: "icosahedron", position: [0, 1.2, 0], scale: [1.6, 1.6, 1.6],
          color: "#ffffff", metalness: 1, roughness: 0.02, envMapIntensity: 1.6, spin: [0.1, 0.4, 0.1] }),
      o({ name: "ring", type: "torus", position: [0, 1.2, 0], rotation: [Math.PI / 2, 0, 0],
          scale: [2.6, 2.6, 2.6], color: "#cccccc", metalness: 1, roughness: 0.05, spin: [0, 0.3, 0] }),
    ],
  },
  {
    id: "glass-garden",
    name: "Glass Garden",
    tags: ["glass", "transmission", "soft"],
    background: "#e8eef5", environment: "park", exposure: 1.2,
    fx: { bloom: true, bloomIntensity: 0.4, vignette: false },
    lights: rigs.studio(),
    objects: [
      ground("#dde4ec", { roughness: 0.6 }),
      o({ name: "vase", type: "torusKnot", position: [-1.2, 1.2, 0], scale: [0.8, 0.8, 0.8],
          color: "#ffffff", metalness: 0, roughness: 0.05, transmission: 1, ior: 1.52, thickness: 1.2,
          clearcoat: 1, spin: [0, 0.2, 0] }),
      o({ name: "orb", type: "sphere", position: [1.4, 1, 0.5], scale: [1.2, 1.2, 1.2],
          color: "#bfe7ff", metalness: 0, roughness: 0.02, transmission: 0.95, ior: 1.45, thickness: 1.5,
          clearcoat: 1 }),
      o({ name: "shard", type: "octahedron", position: [0, 0.8, -1.5], scale: [0.9, 1.4, 0.9],
          color: "#ffffff", metalness: 0, roughness: 0.1, transmission: 0.9, ior: 1.5, thickness: 1, spin: [0, 0.15, 0.1] }),
    ],
  },
  {
    id: "neon-cathedral",
    name: "Neon Cathedral",
    tags: ["neon", "synthwave", "glow"],
    background: "#0a0028", environment: "night", exposure: 1.3,
    fx: { bloom: true, bloomIntensity: 1.6, chromatic: true, chromaticOffset: 0.003, vignette: true },
    lights: rigs.neon(),
    objects: [
      ground("#0a0028", { texture: "grid", textureRepeat: 8, color: "#150040", metalness: 0.4, roughness: 0.3 }),
      o({ name: "tower", type: "cylinder", position: [0, 2, 0], scale: [0.6, 4, 0.6],
          color: "#000000", emissive: "#ff00aa", emissiveIntensity: 1.6, metalness: 0.5, roughness: 0.3 }),
      o({ name: "ring_a", type: "torus", position: [0, 1.5, 0], rotation: [Math.PI / 2, 0, 0],
          scale: [1.6, 1.6, 1.6], color: "#000", emissive: "#00ffff", emissiveIntensity: 2, metalness: 0.6, roughness: 0.2, spin: [0, 0.6, 0] }),
      o({ name: "ring_b", type: "torus", position: [0, 2.5, 0], rotation: [Math.PI / 2, 0, 0],
          scale: [1.2, 1.2, 1.2], color: "#000", emissive: "#ff00aa", emissiveIntensity: 2, metalness: 0.6, roughness: 0.2, spin: [0, -0.5, 0] }),
    ],
  },
  {
    id: "molten-gold",
    name: "Molten Gold",
    tags: ["gold", "luxury", "warm"],
    background: "#1a0a00", environment: "sunset", exposure: 1,
    fx: { bloom: true, bloomIntensity: 0.9, vignette: true },
    lights: rigs.golden(),
    objects: [
      ground("#1a0a00", { metalness: 0.2, roughness: 0.7 }),
      o({ name: "ingot", type: "box", position: [0, 0.6, 0], scale: [2, 0.6, 1.2],
          color: "#ffcc66", metalness: 1, roughness: 0.18, envMapIntensity: 1.2 }),
      o({ name: "coin_a", type: "cylinder", position: [-1.4, 0.3, 1], rotation: [Math.PI / 2, 0, 0], scale: [0.6, 0.05, 0.6],
          color: "#ffcc66", metalness: 1, roughness: 0.2, spin: [0, 0.4, 0] }),
      o({ name: "coin_b", type: "cylinder", position: [1.5, 0.3, -1], rotation: [Math.PI / 2, 0, 0], scale: [0.6, 0.05, 0.6],
          color: "#ffcc66", metalness: 1, roughness: 0.2, spin: [0, -0.4, 0] }),
    ],
  },
  {
    id: "arctic-bloom",
    name: "Arctic Bloom",
    tags: ["ice", "cool", "soft"],
    background: "#dfeefb", environment: "dawn", exposure: 1.1,
    fx: { bloom: true, bloomIntensity: 0.5, vignette: false },
    lights: rigs.arctic(),
    objects: [
      ground("#cee2f2"),
      o({ name: "ice_a", type: "icosahedron", position: [-1.2, 1.2, 0], scale: [1.2, 1.2, 1.2],
          color: "#cfe9ff", metalness: 0, roughness: 0.1, transmission: 0.85, ior: 1.31, thickness: 1.2, clearcoat: 1, spin: [0, 0.15, 0] }),
      o({ name: "ice_b", type: "octahedron", position: [1.4, 1, 0.5], scale: [1, 1.6, 1],
          color: "#e6f3ff", metalness: 0, roughness: 0.08, transmission: 0.9, ior: 1.31, thickness: 1, spin: [0.1, 0.2, 0] }),
    ],
  },
  {
    id: "carbon-deck",
    name: "Carbon Deck",
    tags: ["carbon", "tech", "matte"],
    background: "#080a0d", environment: "warehouse", exposure: 0.95,
    fx: { bloom: true, bloomIntensity: 0.4, vignette: true },
    lights: rigs.studio(),
    objects: [
      ground("#0a0d10", { texture: "carbon", textureRepeat: 6, color: "#1a1a1a", metalness: 0.5, roughness: 0.4, clearcoat: 0.5 }),
      o({ name: "block", type: "box", position: [0, 0.7, 0], scale: [1.6, 1.4, 1.6],
          color: "#1a1a1a", metalness: 0.6, roughness: 0.3, texture: "carbon", textureRepeat: 2, clearcoat: 0.6 }),
      o({ name: "accent", type: "torus", position: [0, 0.7, 0], rotation: [Math.PI / 2, 0, 0],
          scale: [1.4, 1.4, 1.4], color: "#000", emissive: "#ff3a3a", emissiveIntensity: 1.8, metalness: 0.4, roughness: 0.2, spin: [0, 0.4, 0] }),
    ],
  },
  {
    id: "lava-core",
    name: "Lava Core",
    tags: ["fire", "emissive", "energy"],
    background: "#10000a", environment: "night", exposure: 1.2,
    fx: { bloom: true, bloomIntensity: 1.8, chromatic: true, chromaticOffset: 0.002, vignette: true },
    lights: [
      { name: "ambient", type: "ambient", position: [0, 0, 0], color: "#330000", intensity: 0.4, castShadow: false },
      { name: "glow", type: "point", position: [0, 1.5, 0], color: "#ff5500", intensity: 6, castShadow: false, distance: 15, decay: 1.5 },
      { name: "rim", type: "directional", position: [-3, 4, -3], color: "#ff2200", intensity: 0.6, castShadow: false },
    ],
    objects: [
      ground("#10000a", { metalness: 0.4, roughness: 0.5 }),
      o({ name: "core", type: "sphere", position: [0, 1.5, 0], scale: [1.4, 1.4, 1.4],
          color: "#ff3000", emissive: "#ff6a00", emissiveIntensity: 2, metalness: 0, roughness: 0.7, texture: "noise", textureRepeat: 4, spin: [0.1, 0.3, 0.1] }),
      o({ name: "crust", type: "torusKnot", position: [0, 1.5, 0], scale: [1.8, 1.8, 1.8],
          color: "#220000", metalness: 0.3, roughness: 0.9, spin: [0, -0.2, 0] }),
    ],
  },
  {
    id: "vapor-grid",
    name: "Vapor Grid",
    tags: ["retro", "grid", "synth"],
    background: "#1a002a", environment: "sunset", exposure: 1.2,
    fx: { bloom: true, bloomIntensity: 1.4, chromatic: true, chromaticOffset: 0.003, vignette: true },
    lights: rigs.neon(),
    objects: [
      ground("#1a002a", { texture: "grid", textureRepeat: 16, color: "#ff00aa", emissive: "#ff00aa", emissiveIntensity: 0.4, metalness: 0.3, roughness: 0.5 }),
      o({ name: "sun", type: "sphere", position: [0, 1.5, -3], scale: [2, 2, 2],
          color: "#ff6a00", emissive: "#ff3300", emissiveIntensity: 1.5, metalness: 0, roughness: 0.5 }),
      o({ name: "pillar_a", type: "box", position: [-2.5, 1, -1], scale: [0.4, 2, 0.4],
          color: "#000", emissive: "#00ffff", emissiveIntensity: 1.5, metalness: 0.5, roughness: 0.3 }),
      o({ name: "pillar_b", type: "box", position: [2.5, 1, -1], scale: [0.4, 2, 0.4],
          color: "#000", emissive: "#ff00ff", emissiveIntensity: 1.5, metalness: 0.5, roughness: 0.3 }),
    ],
  },
  {
    id: "ceramic-pop",
    name: "Ceramic Pop",
    tags: ["ceramic", "pastel", "playful"],
    background: "#ffe9e9", environment: "studio", exposure: 1.1,
    fx: { bloom: true, bloomIntensity: 0.4, vignette: false },
    lights: rigs.studio(),
    objects: [
      ground("#ffe1e1"),
      o({ name: "blob_a", type: "sphere", position: [-1.2, 1, 0], scale: [1.2, 1.2, 1.2],
          color: "#ff80a0", metalness: 0, roughness: 0.18, clearcoat: 1, spin: [0, 0.3, 0] }),
      o({ name: "blob_b", type: "torusKnot", position: [1.3, 1.1, 0.4], scale: [0.8, 0.8, 0.8],
          color: "#80c4ff", metalness: 0, roughness: 0.18, clearcoat: 1, spin: [0.1, 0.4, 0] }),
      o({ name: "blob_c", type: "cone", position: [0, 1.4, -1.4], scale: [0.8, 1.4, 0.8],
          color: "#ffd070", metalness: 0, roughness: 0.18, clearcoat: 1, spin: [0, 0.3, 0] }),
    ],
  },
  {
    id: "circuit-city",
    name: "Circuit City",
    tags: ["tech", "circuit", "neon"],
    background: "#000510", environment: "night", exposure: 1,
    fx: { bloom: true, bloomIntensity: 1.2, vignette: true },
    lights: rigs.neon(),
    objects: [
      ground("#000510", { texture: "circuit", textureRepeat: 4, color: "#001a1a", metalness: 0.4, roughness: 0.4 }),
      o({ name: "tower_a", type: "box", position: [-1.5, 1.2, 0], scale: [0.8, 2.4, 0.8],
          color: "#001a1a", emissive: "#00ffaa", emissiveIntensity: 0.8, metalness: 0.6, roughness: 0.3 }),
      o({ name: "tower_b", type: "box", position: [1.5, 0.8, 0], scale: [0.8, 1.6, 0.8],
          color: "#001a1a", emissive: "#0088ff", emissiveIntensity: 1, metalness: 0.6, roughness: 0.3 }),
      o({ name: "tower_c", type: "box", position: [0, 1.6, -1.5], scale: [0.6, 3.2, 0.6],
          color: "#001a1a", emissive: "#ff00aa", emissiveIntensity: 0.8, metalness: 0.6, roughness: 0.3 }),
    ],
  },
  {
    id: "say-hello",
    name: "Say Hello",
    tags: ["text", "type", "wide"],
    background: "#7cc1ff", environment: "city", exposure: 1.1,
    fx: { bloom: true, bloomIntensity: 0.6, vignette: false },
    lights: rigs.studio(),
    objects: [
      ground("#7cc1ff"),
      o({ name: "title", type: "text", text: "HELLO", position: [0, 1.4, 0], scale: [1.4, 1.4, 1.4],
          color: "#ffffff", metalness: 0.4, roughness: 0.4, clearcoat: 0.5, spin: [0, 0.3, 0] }),
    ],
  },
  {
    id: "system-error",
    name: "System Error",
    tags: ["pixel", "monitor", "glitch"],
    background: "#0019ff", environment: "night", exposure: 1,
    fx: { bloom: false, pixelate: true, pixelSize: 6, vignette: true, noise: true, noiseOpacity: 0.25 },
    showGrid: false,
    lights: rigs.studio(),
    objects: [
      o({ name: "title", type: "text", text: "SYSTEM", position: [0, 1.6, 0],
          color: "#ffffff", metalness: 0, roughness: 1 }),
      o({ name: "subtitle", type: "text", text: "ERROR", position: [0, 0.3, 0], scale: [0.7, 0.7, 0.7],
          color: "#ffffff", metalness: 0, roughness: 1 }),
    ],
  },
  {
    id: "dream-stack",
    name: "Dream Stack",
    tags: ["chrome", "pastel", "stack"],
    background: "#0a0011", environment: "night", exposure: 1.1,
    fx: { bloom: true, bloomIntensity: 1.4, chromatic: true, chromaticOffset: 0.003, vignette: true },
    lights: rigs.noir(),
    objects: [
      ground("#0a0011"),
      o({ name: "a", type: "box", position: [-1, 0.4, 0], rotation: [0.3, 0.5, 0], scale: [1.2, 0.4, 1.4],
          color: "#ffd1f7", metalness: 1, roughness: 0.1, spin: [0, 0.4, 0] }),
      o({ name: "b", type: "box", position: [0, 1, 0], rotation: [0.4, 0.6, 0], scale: [1.2, 0.4, 1.4],
          color: "#a78bfa", metalness: 1, roughness: 0.1, spin: [0, 0.4, 0] }),
      o({ name: "c", type: "box", position: [1, 1.6, 0], rotation: [0.5, 0.7, 0], scale: [1.2, 0.4, 1.4],
          color: "#fde68a", metalness: 1, roughness: 0.1, spin: [0, 0.4, 0] }),
    ],
  },
  {
    id: "concrete-brutalism",
    name: "Brutalist Block",
    tags: ["concrete", "raw", "minimal"],
    background: "#9a9a9a", environment: "city", exposure: 1,
    fx: { bloom: false, vignette: true },
    lights: rigs.studio(),
    objects: [
      ground("#888", { texture: "concrete", textureRepeat: 6, color: "#888", metalness: 0, roughness: 0.95 }),
      o({ name: "slab_a", type: "box", position: [-1.2, 0.5, 0], scale: [1, 1, 2.4],
          color: "#aaa", metalness: 0, roughness: 0.95, texture: "concrete", textureRepeat: 1.5 }),
      o({ name: "slab_b", type: "box", position: [0.8, 1.3, 0], scale: [2.4, 0.6, 2.4],
          color: "#bbb", metalness: 0, roughness: 0.95, texture: "concrete", textureRepeat: 1.5 }),
    ],
  },
  {
    id: "holo-prism",
    name: "Holo Prism",
    tags: ["hologram", "prism", "future"],
    background: "#000814", environment: "night", exposure: 1.2,
    fx: { bloom: true, bloomIntensity: 1.6, chromatic: true, chromaticOffset: 0.004, vignette: true },
    lights: rigs.neon(),
    objects: [
      ground("#000814"),
      o({ name: "prism", type: "octahedron", position: [0, 1.4, 0], scale: [1.6, 2.2, 1.6],
          color: "#22e0ff", metalness: 0.6, roughness: 0.1, transmission: 0.4, clearcoat: 1,
          emissive: "#22e0ff", emissiveIntensity: 0.7, spin: [0.1, 0.4, 0] }),
      o({ name: "shadow", type: "torus", position: [0, 0.05, 0], rotation: [Math.PI / 2, 0, 0], scale: [2, 2, 2],
          color: "#000", emissive: "#22e0ff", emissiveIntensity: 1, metalness: 0.5, roughness: 0.3 }),
    ],
  },
  {
    id: "garden-of-orbs",
    name: "Garden of Orbs",
    tags: ["soft", "scatter", "calm"],
    background: "#f0e5d8", environment: "park", exposure: 1.1,
    fx: { bloom: true, bloomIntensity: 0.5, vignette: false },
    lights: rigs.golden(),
    objects: [
      ground("#e6dcc8"),
      o({ name: "o1", type: "sphere", position: [-1.5, 0.5, 0.5], scale: [0.6, 0.6, 0.6],
          color: "#d97757", metalness: 0, roughness: 0.4, clearcoat: 0.4 }),
      o({ name: "o2", type: "sphere", position: [0, 0.7, -0.5], scale: [0.8, 0.8, 0.8],
          color: "#5a8a5c", metalness: 0, roughness: 0.4, clearcoat: 0.4 }),
      o({ name: "o3", type: "sphere", position: [1.6, 0.5, 0.6], scale: [0.7, 0.7, 0.7],
          color: "#c9a84c", metalness: 0.6, roughness: 0.3, clearcoat: 0.5 }),
      o({ name: "o4", type: "sphere", position: [0.6, 1.4, -1.4], scale: [0.5, 0.5, 0.5],
          color: "#0a0a0a", metalness: 0.9, roughness: 0.1 }),
    ],
  },
  {
    id: "knot-symphony",
    name: "Knot Symphony",
    tags: ["topology", "complex", "studio"],
    background: "#10131a", environment: "studio", exposure: 1,
    fx: { bloom: true, bloomIntensity: 0.7, vignette: true },
    lights: rigs.studio(),
    objects: [
      ground("#10131a", { metalness: 0.3, roughness: 0.5 }),
      o({ name: "knot", type: "torusKnot", position: [0, 1.4, 0], scale: [1.2, 1.2, 1.2],
          color: "#ff80c0", metalness: 1, roughness: 0.1, envMapIntensity: 1.4, spin: [0, 0.4, 0.1] }),
    ],
  },
  {
    id: "minimal-product",
    name: "Minimal Product",
    tags: ["product", "white", "studio"],
    background: "#f4f4f6", environment: "studio", exposure: 1.1,
    fx: { bloom: false, vignette: false },
    lights: rigs.studio(),
    objects: [
      ground("#eeeef0"),
      o({ name: "product", type: "cylinder", position: [0, 0.9, 0], scale: [0.8, 1.8, 0.8],
          color: "#ffffff", metalness: 0.2, roughness: 0.25, clearcoat: 1, clearcoatRoughness: 0.05 }),
      o({ name: "cap", type: "cylinder", position: [0, 1.85, 0], scale: [0.82, 0.1, 0.82],
          color: "#222222", metalness: 0.6, roughness: 0.3 }),
    ],
  },
  {
    id: "cosmic-bloom",
    name: "Cosmic Bloom",
    tags: ["space", "particles", "ethereal"],
    background: "#000010", environment: "night", exposure: 1.3,
    fx: { bloom: true, bloomIntensity: 2, vignette: true },
    lights: [
      { name: "ambient", type: "ambient", position: [0, 0, 0], color: "#220033", intensity: 0.3, castShadow: false },
      { name: "core", type: "point", position: [0, 1.5, 0], color: "#ff66ff", intensity: 5, castShadow: false, distance: 12, decay: 2 },
    ],
    objects: [
      o({ name: "core", type: "sphere", position: [0, 1.5, 0], scale: [0.6, 0.6, 0.6],
          color: "#fff", emissive: "#ff66ff", emissiveIntensity: 4, metalness: 0, roughness: 0.5 }),
      o({ name: "petal_a", type: "torus", position: [0, 1.5, 0], rotation: [0, 0, 0], scale: [1.4, 1.4, 1.4],
          color: "#000", emissive: "#aa00ff", emissiveIntensity: 1.6, metalness: 0.5, roughness: 0.3, spin: [0, 0.5, 0] }),
      o({ name: "petal_b", type: "torus", position: [0, 1.5, 0], rotation: [Math.PI / 2, 0, 0], scale: [1.4, 1.4, 1.4],
          color: "#000", emissive: "#00aaff", emissiveIntensity: 1.6, metalness: 0.5, roughness: 0.3, spin: [0.5, 0, 0] }),
      o({ name: "petal_c", type: "torus", position: [0, 1.5, 0], rotation: [0, 0, Math.PI / 2], scale: [1.4, 1.4, 1.4],
          color: "#000", emissive: "#ffaa00", emissiveIntensity: 1.6, metalness: 0.5, roughness: 0.3, spin: [0, 0, 0.5] }),
    ],
  },
  {
    id: "wireframe-lab",
    name: "Wireframe Lab",
    tags: ["wire", "tech", "lab"],
    background: "#020a14", environment: "warehouse", exposure: 1,
    fx: { bloom: true, bloomIntensity: 0.8, vignette: true },
    lights: rigs.studio(),
    objects: [
      ground("#020a14", { texture: "grid", textureRepeat: 20, color: "#001428", metalness: 0.4, roughness: 0.5 }),
      o({ name: "ico", type: "icosahedron", position: [-1.4, 1.2, 0], scale: [1, 1, 1],
          color: "#000", emissive: "#00ffaa", emissiveIntensity: 1.4, metalness: 0.5, roughness: 0.3, spin: [0.2, 0.3, 0] }),
      o({ name: "dodec", type: "dodecahedron", position: [1.4, 1.2, 0], scale: [1, 1, 1],
          color: "#000", emissive: "#00aaff", emissiveIntensity: 1.4, metalness: 0.5, roughness: 0.3, spin: [0, 0.4, 0.2] }),
    ],
  },
  {
    id: "brick-and-mortar",
    name: "Brick & Mortar",
    tags: ["brick", "warm", "scene"],
    background: "#3a1a10", environment: "sunset", exposure: 1,
    fx: { bloom: true, bloomIntensity: 0.5, vignette: true },
    lights: rigs.golden(),
    objects: [
      ground("#3a1a10", { texture: "brick", textureRepeat: 4, color: "#9a3a20", metalness: 0, roughness: 0.9 }),
      o({ name: "wall", type: "box", position: [0, 1.5, -1.5], scale: [4, 3, 0.3],
          color: "#9a3a20", metalness: 0, roughness: 0.9, texture: "brick", textureRepeat: 3 }),
      o({ name: "lamp", type: "sphere", position: [0, 2.4, 0], scale: [0.4, 0.4, 0.4],
          color: "#000", emissive: "#ffaa44", emissiveIntensity: 3, metalness: 0, roughness: 0.5 }),
    ],
  },
];
